name: Build and deploy Python app to Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          mkdir -p .python_packages/lib/site-packages
          pip install -r requirements.txt --target=.python_packages/lib/site-packages

      - name: Create zip for deployment (includes .python_packages)
        run: |
          zip -r release.zip . -x "*.git*" ".github*" "venv/*" "__pycache__*" "*.pyc" "*.pyo"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'rag-function1'
          package: 'release.zip'
